services:
  laravel:
    build:
      context: ..
      dockerfile: infra/docker/laravel/prod.Dockerfile
    container_name: learncircle-laravel
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: learncircle
      DB_USERNAME: user
      DB_PASSWORD: pass
    depends_on:
      - db
      - redis

  node:
    build:
      context: ..
      dockerfile: infra/docker/node/prod.Dockerfile
    container_name: learncircle-node
    restart: unless-stopped
    environment:
      NODE_ENV: production
    depends_on:
      - laravel

  vue:
    build:
      context: ..
      dockerfile: infra/docker/vue/prod.Dockerfile
    container_name: learncircle-vue
    restart: unless-stopped
    depends_on:
      - laravel
      - node

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: learncircle
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: learncircle-redis

  nginx:
    image: nginx:alpine
    container_name: learncircle-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - laravel
      - node
      - vue

volumes:
  db_data:
